server:
  port: 8100
  session:
    cookie:
      http-only: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  activiti:
    check-process-definitions: false
#   process-definition-location-prefix: classpath:/processes/
#   process-definition-location-suffixes:
#      - **.bpmn
#      - **.bpmn20.xml